/**
 * Centralised UI copy. i18n is deferred (PRD §5.3 asks for EN + Bahasa Indonesia);
 * keeping every user-facing string here makes adding `next-intl` later a drop-in.
 */
export const strings = {
  app: {
    name:
      process.env.NEXT_PUBLIC_APP_NAME ??
      "Climate Action & Narrative Validation System",
    shortName: "CANVAS",
    tagline: "A structured immune system for your information environment.",
  },
  nav: {
    overview: "Overview",
    claims: "Claim Repository Bank",
    policies: "Policy & Project Bank",
    alerts: "Alert Page",
    admin: "Admin Settings",
    coordinatedNetwork: "Coordinated-Network Detector",
  },
  auth: {
    loginTitle: "Sign in",
    registerTitle: "Create an account",
    email: "Email",
    name: "Full name",
    password: "Password",
    passwordHint: "8–128 characters.",
    signIn: "Sign in",
    register: "Register",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    signingIn: "Signing in…",
    registering: "Creating account…",
    logout: "Log out",
    errRequired: "Email, name and password are required.",
    errPasswordLength: "Password must be at least 8 characters.",
    errInvalid: "Incorrect email or password.",
    errTaken: "That email is already registered.",
  },
  common: {
    seeAll: "See all",
    search: "Search",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    saved: "Saved",
    copy: "Copy",
    copied: "Copied to clipboard",
    download: "Download file",
    back: "Back",
    loading: "Loading…",
    noResults: "No results",
    allTopics: "All Topics",
    allYears: "All Year",
    allStatus: "All Status",
    lastFetched: "Last fetched",
    whatIsThis: "What is this?",
    edit: "Edit",
    notAvailable: "—",
  },
  claims: {
    pageTitle: "Claim Repository Bank",
    s1Title: "Existing Claims",
    s1Subtitle: "Generic Claim — confirmed circulating in public discourse",
    s2Title: "Non-Existing Claims",
    s2Subtitle: "Synthetic Claim — predicted by AI as likely to emerge",
    genericTag: "Existing Claim",
    syntheticTag: "Synthetic Claim",
    searchS1: "Search existing claims…",
    searchS2: "Search predicted claims…",
    searchAll: "Search claim statements…",
    firstCaught: "First caught",
    created: "Predicted",
    negativeStatements: "Negative statements",
    positiveStatements: "Positive statements",
    claimStatement: "Claim Statement",
    claimStatus: "Claim Status",
    scoreBreakdown: "Score Breakdown",
    topAccounts: "Top 5 Accounts",
    topAccountsNote:
      "Accounts contributing most to this claim's spread (supporting side).",
    debunkActivity: "Debunk Activity",
    prebunkActivity: "Prebunk Activity",
    correlatedPolicies: "Correlated Public Policies",
    correlatedPolicy: "Correlated Public Policy",
    noPolicies: "No correlated policies yet.",
    dormant: "Dormant",
    dormantHint: "No supporting or opposing volume — score not discounted.",
    eiSupporting: "EI (supporting)",
    eiOpposing: "EI (opposing) · diagnostic",
    seeAllGeneric: "All existing claims",
    seeAllSynthetic: "All predicted claims",
    activityUnavailable: "No AI draft has been generated for this claim yet.",
    statementsTitle: "Source statements",
    stanceAll: "All",
    stancePositive: "Supporting",
    stanceNegative: "Opposing",
    stanceNeutral: "Neutral",
    noStatements: "No statements match this filter.",
    noTopAccounts: "No supporting-side accounts have been ranked yet.",
    scoreHistoryTitle: "FinalClaimScore history",
    scoreHistoryEmpty:
      "History starts when a claim joins the Alert watchlist — add it with the bell icon to begin tracking.",
    notScored: "Not scored",
    syntheticNotScored:
      "Synthetic claims are predictions and are not scored — no score breakdown, statements or top accounts exist for them.",
    harmBreakdown: "Harm breakdown",
    harmConfirmed: "Harm assessment confirmed — the claim has been rescored.",
    harmHumanConfirmed: "Human confirmed",
    loadMore: "Load more",
    reviewTitle: "Review",
    reviewNotes: "Reviewer notes",
    reviewNotesPlaceholder: "Why this status? Max 2000 characters.",
    reviewNever: "No review recorded yet — set a status to add one.",
    reviewOverlayNote:
      "One note is kept per claim: saving replaces the previous one rather than adding to a history.",
    reviewSaved: "Review saved",
    reviewBy: "by",

    /* --- v1.5 --- */
    scoreFormulaLabel: "How this score is calculated",
    scoreFormulaFallback:
      "FinalClaimScore combines five weighted parameters — Reach, Velocity, Falseness Confidence, Harm Severity and Emotional Intensity — into a ClaimScore, then discounts it by the Net Pushback Ratio, which lowers the score of a claim the public is already pushing back on.",
    harmRowEdit: "Edit",
    harmRowEditLabel: "Edit the four Harm sub-scores",
    harmEditTitle: "Harm sub-scores",
    harmEditSlow:
      "Saving rescores the claim through the AI service, so this takes a few seconds. Only values you changed are sent; the rest keep the AI's own classification.",
    harmEdited: "Edited",
    harmEditedTag: "Harm edited by a reviewer",
    harmEditedBy: "Edited by",
    harmEditedPrevious: "AI's original values",
    harmRangeError: "Each sub-score must be between 0 and 100.",
    debunkSegmentsTitle: "Debunk Activity — segmented recommendations",
    debunkSegmentsHint:
      "One tailored draft per audience segment, most-exposed first. Each is written for that segment's own framing — copy the one you are actually addressing.",
    debunkSegmentCount: "audience segments",
  },
  policies: {
    pageTitle: "Policy & Project Bank",
    listTitle: "Public Policies",
    addPolicy: "Add Public Policy",
    addPolicyTitle: "Add a public policy",
    policyName: "Public policy name",
    policyNamePlaceholder: "e.g. Central Business District Congestion Charge",
    rolledOutDate: "Rolled-out date",
    file: "Policy document",
    fileHint: "PDF or Word document",
    fileReject: "Only PDF or Word documents are accepted.",
    search: "Search policies…",
    rolledOut: "Rolled Out",
    notRolledOut: "Not Rolled Out",
    processing: "Processing",
    processingHint:
      "AI matchmaking is linking and predicting claims for this policy. It will be available shortly.",
    exposureGeneric: "Correlated Existing Claims",
    exposureSynthetic: "Predicted Synthetic Claims",
    noGeneric: "No existing claims are linked to this policy yet.",
    noSynthetic: "No predicted claims have been generated for this policy yet.",
    description: "Description",
    descriptionPlaceholder: "Optional summary of what this policy does.",
    linkedClaims: "linked claims",
    processingPending: "Queued",
    processingFailed: "Matchmaking failed",
    processingSkipped: "No AI service",
    processingSkippedHint:
      "No AI service is configured for this deployment, so no claims were matched or predicted. This is not an error.",
    failedHint:
      "AI matchmaking did not complete. Retry it to re-queue the job — the attempt counter resets.",
    rematch: "Retry matchmaking",
    rematchQueued: "Matchmaking re-queued",
    rematchRunning: "Matchmaking is already running for this policy.",
    aiUnavailable: "No AI service is configured, so matchmaking cannot run.",
    edit: "Edit policy",
    editTitle: "Edit public policy",
    updated: "Policy updated",
    delete: "Delete policy",
    deleteTitle: "Delete this policy?",
    deleteBody:
      "The policy record and its stored document are removed. Claims the AI service linked to it are not deleted.",
    deleted: "Policy deleted",
    downloadFailed: "The document could not be downloaded.",
    downloadMockUnavailable:
      "File downloads need the live backend — they are not available in mock mode.",
    filterStatus: "Rollout status",
    replaceFile: "Replace document",
    replaceFileTitle: "Replace the policy document",
    replaceFileHint:
      "The policy keeps its id and every claim correlation. AI matchmaking re-runs against the new document.",
    replaceFileDone: "Document replaced — matchmaking re-queued",
    lastActivity: "Latest linked-claim activity",
  },
  alerts: {
    pageTitle: "Alert Page",
    chartTitle: "FinalClaimScore over time",
    legendTitle: "Key",
    legendEmpty: "Tick a claim in the table below to plot it.",
    watchlistTitle: "Watchlist",
    search: "Search watchlist…",
    colId: "ID",
    colChart: "Chart",
    colStatement: "Claim Statement",
    colCreated: "Claim Created Date",
    colStatus: "Status",
    overThreshold: "Over Threshold",
    underThreshold: "Under Threshold",
    empty: "Your watchlist is empty. Add claims from the Claim Repository Bank using the bell icon.",
    colTopic: "Topic",
    colCreatedDate: "Claim Created Date",
    colAdded: "Added",
    colRemove: "Remove",
    thresholdNote: "Compared against the global threshold of",
    granularity: "Granularity",
    granularityDay: "Day",
    granularityWeek: "Week",
    granularityMonth: "Month",
    granularityYear: "Year",
    chartEmpty:
      "No history yet for the ticked claims. Snapshots are captured hourly; use \"Snapshot scores now\" on Admin Settings to force one.",
    remove: "Remove from watchlist",
    removed: "Removed from watchlist",
    chartToggleFailed: "Could not update the chart selection.",

    /* --- v1.5 --- */
    justCrossed: "Just crossed",
    crossedUp: "Crossed above the threshold",
    crossedDown: "Crossed below the threshold",
    colLastMoved: "Last moved",
    notificationsLabel: "threshold crossings",
  },
  admin: {
    pageTitle: "Admin Settings",
    thresholdTitle: "Alert Threshold",
    thresholdDesc:
      "Global 0–100 threshold. A watched claim is \"Over Threshold\" on the Alert page when its FinalClaimScore is at or above this value.",
    thresholdLabel: "Threshold value",
    testUtilsTitle: "MVP Test Utilities",
    generateClaim: "Generate Generic Claim",
    generateClaimDesc:
      "Inserts one fully-populated Existing/Generic claim for demo and testing. Updates the \"last fetched\" time on the Claim Repository Bank.",
    generateClaimUtility: "Testing / MVP utility",
    generated: "A sample generic claim was added.",
    generateClaimTopic: "Pin to topic (optional)",
    generateClaimAnyTopic: "Any topic",
    snapshotTitle: "Snapshot scores now",
    snapshotDesc:
      "Captures a FinalClaimScore snapshot for every watched claim immediately, building Alert-page chart history without waiting for the hourly job.",
    snapshotAction: "Snapshot scores",
    snapshotDone: "score snapshots captured.",
    settingsTitle: "All settings",
    settingsDesc: "Every global setting the backend exposes, with its audit trail.",
    colKey: "Key",
    colValue: "Value",
    colUpdated: "Updated",
    rescoreTitle: "Rescore all claims",
    rescoreDesc:
      "A claim's score moves with wall-clock time even when nothing new arrives — NPR drifts as opposing posts age out of the window. Without a rescore the Alert chart plots the same number every hour.",
    rescoreAction: "Rescore claims",
    rescoreDone: "claims rescored.",
    sampleTitle: "Generate sample data",
    sampleDesc:
      "Populates the databank with fabricated but realistic content, run through the same pipeline real crawled content would be. Until a live crawler exists this is the only way content enters the system.",
    sampleCount: "How many items (1–50)",
    sampleTopicHint: "Topic hint (optional)",
    sampleTopicHintPlaceholder: "e.g. road pricing",
    sampleAction: "Generate content",
    sampleAutoCluster: "Cluster immediately",
    sampleAutoClusterHint:
      "Runs clustering synchronously so the result can report how many claims it produced. Slower.",
    sampleDone: "content items generated —",
    sampleDoneNoCluster: "content items generated. Nothing was clustered.",
    clusterTitle: "Force a clustering pass",
    clusterDesc:
      "Groups content the AI service has ingested but not yet turned into claims. Normally unnecessary — ingestion triggers clustering on its own.",
    clusterAction: "Cluster now",
    reconcileTitle: "Reconcile orphaned rows",
    reconcileDesc:
      "Clears reviews, watchlist entries and snapshots pointing at AI-side claims that no longer exist, and re-queues policies whose AI record is gone. Needed after a reseed on the AI side.",
    reconcileDryRun: "Preview (dry run)",
    reconcileApply: "Apply reconciliation",
    reconcileIrreversible:
      "Nothing here is recoverable. Check the counts against what you expect before applying.",
    f5Title: "Coordinated-Network Detector",
    tabGeneral: "General",
    tabDetector: "Detector",
    tabAllowlist: "Allowlist",
    tabRuns: "Runs & governance",

    /* --- v1.5 --- */
    cityTitle: "Monitored city",
    cityDesc:
      "Which single Indonesian city this instance is monitoring. It scopes every figure on the Overview page, and sets the timezone the detector's report footers are stamped in.",
    cityLabel: "City",
    citySaved: "Monitored city updated — the Overview page has been re-scoped.",
    cityTimezoneNote: "Timezone",
    cityUnset: "No city selected yet",
  },
  overview: {
    pageTitle: "Overview",
    generatedAt: "Computed",
    cityLabel: "Monitoring",
    cityUnset: "No city configured",
    cityUnsetHint:
      "Set the monitored city on Admin Settings to scope this page.",

    ratioTitle: "Claims above the alert threshold",
    ratioSubtitle:
      "Every existing claim, whatever its review status. An unscored claim counts as below — a claim is never escalated on missing data.",
    ratioAbove: "Over threshold",
    ratioBelow: "Under threshold",
    ratioTotal: "existing claims",
    ratioEmpty: "No existing claims have been captured yet.",
    ratioThreshold: "Threshold",

    csiTitle: "Climate Sentiment Index",
    csiSubtitle: "7-day rolling average · higher is healthier",
    csiExplain:
      "Half of this index is the balance of positive against negative climate conversation; the other half is the risk load those conversations carry, inverted so both halves read the same way. A calm-sounding but dangerous conversation cannot score as healthy.",
    csiBandRisky: "Risky",
    csiBandWatch: "Watch",
    csiBandHealthy: "Healthy",
    csiUnavailable: "Index unavailable",
    csiInsufficient: "Insufficient data",
    csiUnavailableFallback:
      "Per-item sentiment has not been provisioned by the AI service yet, so the index cannot be computed. Every other figure on this page is unaffected.",
    csiInsufficientFallback:
      "Too little climate conversation in the window to compute an index. A quiet week must not read as a calm one.",
    csiBreakdown: "Show the breakdown",
    csiBreakdownHide: "Hide the breakdown",
    csiBcs: "Baseline sentiment",
    csiBcsHint: "Positive minus negative conversation, rescaled to 0–100.",
    csiRiskLoad: "Risk load",
    csiRiskLoadHint:
      "Score-weighted volume of claims at or above the risk cutoff. Higher is worse, which is why the index inverts it.",
    csiMomentum: "vs. 24h earlier",
    csiVolume: "Conversation volume",
    csiVolumePositive: "Positive",
    csiVolumeNegative: "Negative",
    csiVolumeNeutral: "Neutral",
    csiWindow: "Window",
    csiRiskCutoff: "Risk cutoff",

    topicsTitle: "Hot topics",
    topicsSubtitle:
      "One box per existing-claim topic, sized by above-threshold count and average score together. Sizes compare topics with each other right now, not with last week.",
    topicsEmpty: "No existing-claim topics to map yet.",
    topicsClaims: "claims",
    topicsAbove: "above threshold",
    topicsAverage: "Average score",
    topicsWeight: "Box weight",
    topicModalTitle: "Topic detail",
    topicMom: "Month on month",
    topicMomEmpty: "Not enough history to compare months.",
    topicRatio: "Above / under ratio",
    topicRatioEmpty: "Nothing is under threshold, so there is no ratio to show.",
    topicCurrentMonth: "This month",
    topicPreviousMonth: "Last month",
    topicOpen: "Open the claim repository filtered to this topic",

    policiesTitle: "Policies attracting the most high-risk claims",
    policiesSubtitle:
      "Ranked by the same combined metric that sizes the topic map.",
    policiesEmpty: "No public policy has correlated existing claims yet.",
    colRank: "#",
    colPolicy: "Public policy",
    colClaims: "Claims",
    colAbove: "Over threshold",
    colAverage: "Avg. score",
    colScore: "Hotness",
    policyAiOnly: "Not in the Policy & Project Bank",
  },

  bell: {
    addTitle: "Add to Alert watchlist?",
    removeTitle: "Remove from Alert watchlist?",
    addBody:
      "This claim will be added to the Alert page watchlist so you can monitor its FinalClaimScore over time.",
    removeBody:
      "This claim will be removed from the Alert page watchlist and unticked from the chart.",
    add: "Add to watchlist",
    remove: "Remove",
    added: "Added to watchlist",
    removed: "Removed from watchlist",
  },
  networks: {
    pageTitle: "Coordinated-Network Detector",
    subtitle:
      "Clusters of accounts that behaved as one unit while amplifying a tracked claim. Behaviour only — never the stance, sentiment or viewpoint of the content.",
    search: "Search label, claim or member handle…",
    showLowConfidence: "Show low-confidence networks",
    lowConfidenceHint:
      "Low-band networks are hidden by default. A high score with only one signal family agreeing is the characteristic shape of a false positive, not of a campaign.",
    lowConfidenceTag: "Low confidence",
    empty: "No coordinated networks match these filters.",
    emptyAll:
      "No coordinated networks have been detected yet. Runs are scheduled, and can also be triggered on demand from Admin Settings.",
    unavailableTitle: "The detector is not available yet",
    unavailableBody:
      "The detection pipeline has not been deployed for this environment, so there are no networks to review. F1–F4 are unaffected.",
    sort: "Sort by",
    sortScore: "Coordination Score",
    sortDetected: "Most recently detected",
    sortAccounts: "Most accounts",
    sortPosts: "Most flagged posts",
    sortRecurrences: "Most recurrences",
    confidenceFilter: "Confidence",
    detectedFrom: "Detected from",
    detectedTo: "Detected to",
    coordinationScore: "Coordination Score",
    signalBreadth: "SignalBreadth",
    signalBreadthHint:
      "How many signal families independently scored 50 or above. The score alone never determines confidence.",
    accounts: "accounts",
    posts: "flagged posts",
    detected: "Detected",
    platforms: "Platforms",
    primaryClaim: "Primary claim",
    recurrenceSeen: "Seen",
    recurrenceSince: "since",
    truncatedRun: "Truncated run",
    truncatedRunHint:
      "This run's candidate set was capped, so recall is known to be incomplete and every network from it is held at Medium confidence.",
    cappedAtMedium: "Capped at Medium",
    cappedAtMediumHint:
      "Two or more signal families were unavailable this run, so confidence is capped regardless of score (PRD 10.6.3 rule 4).",
    detectionWindow: "Detection window",
    detectionRun: "Detection run",
    trigger: "Trigger",
    candidates: "Candidates",
    signalsUnavailable: "Signals unavailable this run",
    whyFlagged: "Why this was flagged",
    whyFlaggedNote:
      "The composite is never shown without this breakdown — a number a policy reviewer cannot interrogate is not evidence.",
    signalUnavailable: "Not measurable this run",
    signalUnavailableHint:
      "This family could not be measured in this run. That is not the same as a score of zero, which would be a measurement.",
    weight: "Weight",
    rawCounts: "Underlying counts",
    confidenceRule: "Banding rule applied",
    clusterStructure: "Cluster structure",
    internalDensity: "Internal density",
    conductance: "Conductance",
    comparisonAccounts: "Comparison accounts",
    claimRelevance: "Claim relevance",
    claimRelevanceNote:
      "Answers a question the signal scores cannot: not “is this coordinated?” but “is this coordinated about our claim?”",
    overlapRatio: "Overlap ratio",
    anchoringShare: "Member anchoring share",
    clusterPosts: "Claim-cluster posts",
    threshold: "threshold",
    secondaryClaims: "Secondary claim links",
    knownLimitations: "Stated limitations",
    linkedClaims: "Linked claims",
    linkedPolicies: "Linked public policies",
    noLinkedPolicies: "No public policies resolve through this network's claims.",
    graphTitle: "Coordination graph",
    graphNote:
      "Layout coordinates come from the stored snapshot, so this figure and the PDF render identically.",
    graphMember: "Cluster member",
    graphComparison: "Unclustered account on the same claim",
    graphAllowlisted: "Declared coordination",
    graphEmpty: "No graph snapshot was stored for this network.",
    graphReduced: "Reduced to k-core",
    edgeWeight: "Edge weight",
    signalDecomposition: "Per-signal decomposition",
    timelineTitle: "Posting timeline",
    timelineBin: "Bin width",
    timelineAnomalous: "statistically anomalous bins",
    timelineEmpty: "No timeline was captured for this network.",
    contentTitle: "Representative content",
    contentNote:
      "Rendered from the evidence snapshot rather than re-fetched, so a post deleted since capture is still shown, marked.",
    contentEmpty: "No representative content was captured for this network.",
    duplicateGroup: "Duplicate group",
    variants: "variants",
    canonicalText: "Canonical text",
    ungrouped: "Posts in no duplicate group",
    capturedAt: "Captured",
    annexTitle: "Account annex",
    annexNote:
      "Every column is a measured behaviour or a graph position. None is a verdict: the system never labels an account automated or inauthentic.",
    annexSearch: "Search handles…",
    annexEmpty: "No accounts match this filter.",
    colHandle: "Handle",
    colPlatform: "Platform",
    colCreated: "Account created",
    colPosts: "Posts in cluster",
    colDuplication: "Duplication rate",
    colInterpost: "Median inter-post",
    colCircadian: "Circadian coverage",
    colCentrality: "Centrality",
    colRole: "Role",
    roleMember: "Member",
    roleComparison: "Comparison",
    exportCsv: "Export CSV",
    exportCsvDone: "Account annex downloaded — the export is logged.",
    accountDrawerTitle: "Why this account is in the network",
    connectingEdges: "Connecting edges",
    accountPosts: "Posts in the cluster",
    reviewTitle: "Review assessment",
    reviewStatus: "Review status",
    reviewReason: "Reason",
    reviewReasonPlaceholder:
      "State what you assessed and what you concluded. Minimum 20 characters.",
    reviewReasonHint:
      "Required, minimum 20 characters. This is the input the allowlist and the recalibration analysis both learn from.",
    reviewReasonTooShort: "A reason of at least 20 characters is required.",
    reviewSaved: "Assessment recorded",
    reviewLogTitle: "Review history",
    reviewLogEmpty: "No assessment has been recorded for this network yet.",
    reviewLogSignalProfile: "Signal profile at the time of this decision",
    changeStatus: "Record assessment",
    reportsTitle: "Reports and evidence",
    generateReport: "Generate report",
    generateReportTitle: "Generate a network report",
    reportType: "Report type",
    reportTypePlatform: "Platform referral",
    reportTypePlatformHint:
      "Behavioural sections and the account annex, no internal commentary. The annex is mandatory here — a referral without the account list is not actionable.",
    reportTypeInternal: "Internal briefing",
    reportTypeInternalHint:
      "Adds analyst notes, review history and linked claim/policy context.",
    reportSections: "Sections",
    sectionGraph: "Graph figure",
    sectionContent: "Content clusters",
    sectionAnnex: "Account annex",
    sectionMethodology: "Methodology appendix",
    redactAnalysts: "Redact analyst names",
    redactAnalystsHint:
      "Removes the generating user's name from the cover and the review history.",
    reportGenerated: "Report generated",
    evidenceBundle: "Export evidence package",
    evidenceBundleHint:
      "A ZIP of the PDF, network.json, accounts.csv, posts.csv and a manifest whose hashes establish the bundle was not modified after generation.",
    bundleGenerated: "Evidence package generated",
    exportBlocked: "Export is not available for this network",
    noReports: "No report has been generated for this network yet.",
    reportVersion: "Version",
    reportChecksum: "SHA-256",
    reportAudit: "Audit entry",
    download: "Download",
    allowlistNetwork: "Mark as legitimate coordination",
    allowlistAccount: "Mark this account as legitimate coordination",
    allowlistTitle: "Declare legitimate coordination",
    allowlistBody:
      "NGOs, newsrooms, unions and grassroots campaigns coordinate openly and by design. Declaring them here excludes them from every future candidate set and suppresses their historical networks.",
    allowlistCategory: "Category",
    allowlistReason: "Reason",
    allowlistReasonPlaceholder:
      "Why is this coordination legitimate? Minimum 10 characters.",
    allowlistReasonTooShort: "A reason of at least 10 characters is required.",
    allowlistDone: "Added to the declared-coordination allowlist",
    allowlistRetroactive:
      "Allowlisting is retroactive. Networks already exported cannot be recalled — a PDF citing an account since allowlisted is already in someone's inbox.",
    disclaimerTitle: "How to read this finding",
    triggerRun: "Run detection on this claim",
    triggerRunQueued: "Detection run queued",
    detectedOnClaim: "Coordinated network detected",
    detectedOnClaimHint:
      "This changes whether the team publicly rebuts the claim or refers it. Rebutting a claim only a handful of accounts are actually making hands it the reach it was engineered to obtain.",
    othersQualify: "other qualifying networks",
    viewNetwork: "View network",

    /* ---------------- [S4] cluster detail ---------------- */
    scoreCaption: "Score",
    clusterDetail: "Cluster detail",
    amplifying: "amplifying",
    policyPrefix: "policy",
    windowAnalysed: "Window analysed",
    accountsLabel: "Accounts",
    postsLabel: "Flagged posts",
    yourAssessment: "Your assessment",
    assessmentGate: "A written reason of at least 20 characters is required.",
    dismissedNoteTitle: "Assessed as organic",
    signalProfile: "Signal profile",
    signalProfileNote:
      "Each family is scored 0–100 and measured independently. What each one measures, the counts behind it, and its weight in the composite are set out in the report.",
    relevanceHeading: "Is this cluster actually about our claim?",
    shapeHeading: "Shape of the cluster",
    postsHeading: "The posts",
    memberAccounts: "Member accounts",
    memberAccountsHint:
      "Select a row to see that account's posts and the links that put it here.",
    relLinkStrength: "Link strength",
    relLinkStrengthNote: "of the cluster's posting sits inside this claim",
    relAnchoring: "Anchoring",
    relAnchoringNote: "of members post about this claim repeatedly",
    relEvidence: "Evidence",
    relEvidenceNote: "posts inside the claim's own cluster",
    relSecondary: "Secondary",
    relSecondaryNote: "other claims this cluster is also linked to",
    gateShort: "gate",
    detailMovedToReport:
      "Method notes, underlying counts, the posting timeline, run parameters and the stated limitations are all in the report.",
    previewReport: "Preview report",
    generatedReports: "Generated reports",
  },
  networkReport: {
    org: "Climate Action & Narrative Validation System",
    title: "Report on coordinated posting behaviour",
    previewTitle: "Report preview",
    previewNote:
      "Rendered from the same snapshot the generated PDF is built from. Nothing here is filled in where the detector recorded no measurement.",
    print: "Print / Save as PDF",
    close: "Close preview",
    reportType: "Report type",
    coverAccounts: "Accounts",
    coverPosts: "Flagged posts",
    coverPeriod: "Period examined",
    coverPlatforms: "Platforms",
    coverBreadth: "Families agreeing",
    coverDetected: "Detected",
    coverIssuedBy: "Reviewed by",
    coverStatus: "Review status",
    pleaseReadFirst: "Please read first",

    secHowToRead: "How to read this report",
    howBehaviour: "It measures behaviour, not opinion",
    howBehaviourBody:
      "Nothing here uses what the posts say, which side they take, or whether they are true. A group coordinating in favour of a city policy is measured exactly the same way.",
    howBreadth: "One number is never enough",
    howBreadthBody:
      "Five behaviours are checked independently. Each has an innocent explanation on its own, so how many agree is reported alongside how high the score is.",
    howNoBots: "No account is called automated",
    howNoBotsBody:
      "The system does not state that any account is automated, inauthentic or malicious, and makes no claim about who operates it. The finding is that these accounts moved together.",
    howSignedOff: "A person signs it off",
    howSignedOffBody:
      "No report is produced automatically. A network must carry a recorded human assessment before it can be exported at all.",

    secFindings: "What was found, in plain words",
    findingsNotSaying: "What this does not say",
    findingsNotSayingBody:
      "This is not a finding that the claim is false, and not a finding that these accounts are fake. It is a finding that they acted together to a degree ordinary coincidence does not explain.",

    secSignals: "The behaviours that were checked",
    signalsIntro:
      "Each family is scored out of 100. Underneath each one is what the detector actually measured.",
    whatWeSaw: "What was measured",
    breadthCaption: "signal families independently scored 50 or above.",
    bandingRule: "Banding rule applied",
    notMeasured: "Could not be measured this run",

    secSignup: "When the accounts were created",
    signupIntro:
      "Each dot is one member account, placed on the date its platform profile was opened.",
    signupMissing: "accounts have no creation date recorded by the platform.",
    signupOldest: "oldest",
    signupNewest: "newest",

    secRelevance: "Is this cluster about our claim?",
    relevanceIntro:
      "A coordinated group may have touched this claim only in passing. These are the figures it had to clear before it could be surfaced at all.",
    shareThisClaim: "this claim",
    shareEverythingElse: "everything else they posted",
    shareGate: "minimum required",

    secTimeline: "When the posting happened",
    timelineIntro:
      "Posts per bin across the detection window. Bins marked in red sit far enough above this cluster's own normal level to be statistically anomalous; the z figure says how far.",

    secGraph: "How the accounts connect",
    graphIntro:
      "Filled marks are cluster members, drawn larger the closer they sit to the centre of the activity. Hollow marks are unclustered accounts posting about the same claim in the same window.",

    secContent: "The posts themselves",
    contentIntro:
      "The largest groups of near-identical posts. The shared span is highlighted so the repetition is visible without reading closely.",

    secAccounts: "The accounts",
    accountsIntro:
      "Member accounts by public handle only. No attempt is made to identify who operates any of them.",
    accountsMore: "further accounts continue in the exported spreadsheet.",

    secInternal: "Internal assessment",
    internalStatus: "Status",
    internalClaim: "Claim record",
    internalPolicies: "Policies affected",
    internalNote: "Assessment note",
    internalHistory: "Assessment history",

    secSettings: "Settings used",
    settingsIntro:
      "The detector configuration in force when this run executed, copied at run time rather than looked up now.",

    secLimits: "What this report cannot tell you",

    secEvidence: "Where the evidence is kept",
    evidenceRun: "Analysis run",
    evidenceSnapshot: "Sealed evidence copy",
    evidenceSnapshotHash: "Fingerprint of that copy",
    evidenceAudit: "Record of this export",
    evidenceNote:
      "The posts and account details were copied and sealed at the moment of detection, before anything could be deleted. The fingerprint lets a recipient confirm the file has not been altered since.",
  },
  networkStatus: {
    unreviewed: "Unreviewed",
    under_review: "Under Review",
    confirmed: "Confirmed",
    dismissed_false_positive: "Dismissed — False Positive",
    action_taken: "Action Taken",
  },
  confidence: {
    high: "High confidence",
    medium: "Medium confidence",
    low: "Low confidence",
  },
  signals: {
    SY: "Synchrony",
    DU: "Duplication",
    CO: "Cohesion",
    PR: "Provenance anomaly",
    AU: "Automation & behavioural anomaly",
  },
  allowlist: {
    title: "Declared-coordination allowlist",
    description:
      "Accounts the team has declared as legitimately coordinating. Seed this during onboarding with the city's known civil-society partners — before the first detection run, not after the first false positive.",
    search: "Search handles…",
    add: "Add account",
    addTitle: "Add an account to the allowlist",
    platform: "Platform",
    platformAccountId: "Platform account ID",
    platformAccountIdHint:
      "Entries are keyed on the platform-issued ID, not the handle — handles get renamed, IDs do not.",
    handle: "Handle",
    category: "Category",
    reason: "Reason",
    edit: "Edit entry",
    remove: "Remove protection",
    removeTitle: "Remove allowlist protection?",
    removeBody:
      "Removing protection lets the detector flag this account again. A reason is required and is stored separately from the addition reason.",
    removeReason: "Removal reason",
    removed: "Allowlist entry removed",
    added: "Allowlist entry added",
    updated: "Allowlist entry updated",
    includeRemoved: "Include removed entries",
    empty: "The allowlist is empty. Seed it before the first detection run.",
    inactive: "Removed",
    ngo: "NGO",
    newsroom: "Newsroom",
    campaign_group: "Campaign group",
    government: "Government",
    union: "Union",
    self_exclusion: "Self-exclusion (city comms)",
    other: "Other",
    phrasesTitle: "Common-phrase exclusions",
    phrasesDescription:
      "Slogans and civic boilerplate excluded from duplication scoring, so a shared campaign hashtag is not read as content duplication.",
    phrase: "Phrase",
    phraseNotes: "Notes",
    addPhrase: "Add phrase",
    phraseAdded: "Phrase added",
    phraseRemoved: "Phrase removed",
    noPhrases: "No phrases are excluded yet.",
  },
  detector: {
    title: "Detector parameters",
    description:
      "Every detection run records the parameter set in force when it executed, so changing a value here never retroactively alters a stored detection.",
    save: "Save parameters",
    saved: "Detector parameters saved",
    noChanges: "No parameters have been changed.",
    weightsSum: "Signal fusion weights",
    weightsSumHint:
      "The five weights must sum to 1.00 — a composite built from weights summing to 0.9 is not on the 0–100 scale it claims to be on.",
    weightsSumCurrent: "Current sum",
    cadenceHint:
      "Consecutive windows must overlap by 50%, so the cadence may not exceed half the window. Otherwise behaviour straddling a boundary is split across two runs and missed by both.",
    selfExclusion: "Self-exclusion accounts",
    selfExclusionHint:
      "The city's own comms estate, managed through the allowlist under its own category.",
    historyTitle: "Parameter change history",
    historyEmpty: "No parameter has been changed yet.",
    cityTimezone: "City timezone",
    cityTimezoneHint:
      "An IANA zone name, e.g. Asia/Jakarta. Report footers carry the generation time in UTC and city-local time.",
    cityTimezoneSaved: "City timezone saved",
    groupWindow: "Window and binning",
    groupText: "Text similarity",
    groupGraph: "Graph construction",
    groupWeights: "Signal fusion",
    groupRelevance: "Claim-relevance gate",
    groupBanding: "Confidence banding",
    groupSchedule: "Scheduling",
    runsTitle: "Detection runs",
    runsEmpty: "No detection run has executed yet.",
    runTrigger: "Trigger",
    runStatus: "Status",
    runWindow: "Window",
    runNetworks: "Networks",
    runOfftopic: "Off-topic",
    runTruncated: "Truncated",
    offtopicTitle: "Off-topic clusters",
    offtopicDescription:
      "Genuinely coordinated clusters that failed the claim-relevance gate — spam rings, engagement farms, unrelated amplification. They are never surfaced in F5 and never exported; a rising rate means the gate needs recalibration.",
    offtopicEmpty: "No cluster has been rejected by the relevance gate.",
    offtopicFailedTest: "Failed test",
    offtopicRate: "Off-topic rate",
    dismissalsTitle: "False-positive analysis",
    dismissalsDescription:
      "Which signals over-trigger. These endpoints report; an admin decides. Automatic weight adjustment risks silent drift in a system whose defensibility rests on stated parameters.",
    precision: "Precision",
    precisionTarget: "target",
    precisionMet: "Meets target",
    precisionMissed: "Below target",
    precisionUnavailable: "Not enough reviewed networks to compute precision yet.",
    meanSignals: "Mean signal scores across dismissals",
    sampleSize: "Sample size",
    windowDays: "Window",
    auditTitle: "Export audit log",
    auditDescription:
      "Every generated report and evidence bundle, with the sections it contained and the redaction settings in force.",
    auditEmpty: "Nothing has been exported yet.",
    colExportType: "Export type",
    colUser: "User",
    colNetwork: "Network",
    colWhen: "When",
  },
  status: {
    unreviewed: "Unreviewed",
    active: "Active",
    inactive: "Inactive",
    action_taken: "Action Taken",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    notFound: "We couldn't find what you were looking for.",
    liveModeUnavailable:
      "The backend API could not be reached. Check NEXT_PUBLIC_API_BASE_URL, or set NEXT_PUBLIC_API_MODE=mock to explore with sample data.",
    unavailable:
      "A backend dependency is unavailable right now. Please try again shortly.",
    unauthorized: "Your session has expired. Please sign in again.",
  },
} as const;
