/**
 * Centralised UI copy. i18n is deferred (PRD §5.3 asks for EN + Bahasa Indonesia);
 * keeping every user-facing string here makes adding `next-intl` later a drop-in.
 */
export const strings = {
  app: {
    name: process.env.NEXT_PUBLIC_APP_NAME ?? "Climate Immune System",
    shortName: "CIS",
    tagline: "A structured immune system for your information environment.",
  },
  nav: {
    claims: "Claim Repository Bank",
    policies: "Public Policy Bank",
    alerts: "Alert Page",
    admin: "Admin Settings",
    coordinatedNetwork: "Coordinated-Network Detector",
  },
  auth: {
    loginTitle: "Sign in",
    registerTitle: "Create an account",
    email: "Email",
    name: "Full name",
    password: "Password",
    passwordHint: "8–128 characters.",
    signIn: "Sign in",
    register: "Register",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    signingIn: "Signing in…",
    registering: "Creating account…",
    logout: "Log out",
    errRequired: "Email, name and password are required.",
    errPasswordLength: "Password must be at least 8 characters.",
    errInvalid: "Incorrect email or password.",
    errTaken: "That email is already registered.",
  },
  common: {
    seeAll: "See all",
    search: "Search",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    saved: "Saved",
    copy: "Copy",
    copied: "Copied to clipboard",
    download: "Download file",
    back: "Back",
    loading: "Loading…",
    noResults: "No results",
    allTopics: "All Topics",
    allYears: "All Year",
    allStatus: "All Status",
    lastFetched: "Last fetched",
  },
  claims: {
    pageTitle: "Claim Repository Bank",
    s1Title: "Existing Claims",
    s1Subtitle: "Generic Claim — confirmed circulating in public discourse",
    s2Title: "Non-Existing Claims",
    s2Subtitle: "Synthetic Claim — predicted by AI as likely to emerge",
    genericTag: "Existing Claim",
    syntheticTag: "Synthetic Claim",
    searchS1: "Search existing claims…",
    searchS2: "Search predicted claims…",
    searchAll: "Search claim statements…",
    firstCaught: "First caught",
    created: "Predicted",
    negativeStatements: "Negative statements",
    positiveStatements: "Positive statements",
    claimStatement: "Claim Statement",
    claimStatus: "Claim Status",
    scoreBreakdown: "Score Breakdown",
    topAccounts: "Top 5 Accounts",
    topAccountsNote:
      "Accounts contributing most to this claim's spread (supporting side).",
    debunkActivity: "Debunk Activity",
    prebunkActivity: "Prebunk Activity",
    correlatedPolicies: "Correlated Public Policies",
    correlatedPolicy: "Correlated Public Policy",
    noPolicies: "No correlated policies yet.",
    dormant: "Dormant",
    dormantHint: "No supporting or opposing volume — score not discounted.",
    eiSupporting: "EI (supporting)",
    eiOpposing: "EI (opposing) · diagnostic",
    seeAllGeneric: "All existing claims",
    seeAllSynthetic: "All predicted claims",
    activityUnavailable: "No AI draft has been generated for this claim yet.",
    statementsTitle: "Source statements",
    stanceAll: "All",
    stancePositive: "Supporting",
    stanceNegative: "Opposing",
    stanceNeutral: "Neutral",
    noStatements: "No statements match this filter.",
    noTopAccounts: "No supporting-side accounts have been ranked yet.",
    scoreHistoryTitle: "FinalClaimScore history",
    scoreHistoryEmpty:
      "History starts when a claim joins the Alert watchlist — add it with the bell icon to begin tracking.",
    notScored: "Not scored",
    syntheticNotScored:
      "Synthetic claims are predictions and are not scored — no score breakdown, statements or top accounts exist for them.",
    harmBreakdown: "Harm breakdown",
    loadMore: "Load more",
    reviewTitle: "Review",
    reviewNotes: "Reviewer notes",
    reviewNotesPlaceholder: "Why this status? Max 2000 characters.",
    reviewNever: "No review recorded yet — set a status to add one.",
    reviewOverlayNote:
      "One note is kept per claim: saving replaces the previous one rather than adding to a history.",
    reviewSaved: "Review saved",
    reviewBy: "by",
  },
  policies: {
    pageTitle: "Public Policy Bank",
    listTitle: "Public Policies",
    addPolicy: "Add Public Policy",
    addPolicyTitle: "Add a public policy",
    policyName: "Public policy name",
    policyNamePlaceholder: "e.g. Central Business District Congestion Charge",
    rolledOutDate: "Rolled-out date",
    file: "Policy document",
    fileHint: "PDF or Word document",
    fileReject: "Only PDF or Word documents are accepted.",
    search: "Search policies…",
    rolledOut: "Rolled Out",
    notRolledOut: "Not Rolled Out",
    processing: "Processing",
    processingHint:
      "AI matchmaking is linking and predicting claims for this policy. It will be available shortly.",
    exposureGeneric: "Correlated Existing Claims",
    exposureSynthetic: "Predicted Synthetic Claims",
    noGeneric: "No existing claims are linked to this policy yet.",
    noSynthetic: "No predicted claims have been generated for this policy yet.",
    description: "Description",
    descriptionPlaceholder: "Optional summary of what this policy does.",
    linkedClaims: "linked claims",
    processingPending: "Queued",
    processingFailed: "Matchmaking failed",
    processingSkipped: "No AI service",
    processingSkippedHint:
      "No AI service is configured for this deployment, so no claims were matched or predicted. This is not an error.",
    failedHint:
      "AI matchmaking did not complete. Retry it to re-queue the job — the attempt counter resets.",
    rematch: "Retry matchmaking",
    rematchQueued: "Matchmaking re-queued",
    rematchRunning: "Matchmaking is already running for this policy.",
    aiUnavailable: "No AI service is configured, so matchmaking cannot run.",
    edit: "Edit policy",
    editTitle: "Edit public policy",
    updated: "Policy updated",
    delete: "Delete policy",
    deleteTitle: "Delete this policy?",
    deleteBody:
      "The policy record and its stored document are removed. Claims the AI service linked to it are not deleted.",
    deleted: "Policy deleted",
    downloadFailed: "The document could not be downloaded.",
    downloadMockUnavailable:
      "File downloads need the live backend — they are not available in mock mode.",
    filterStatus: "Rollout status",
    replaceFile: "Replace document",
    replaceFileTitle: "Replace the policy document",
    replaceFileHint:
      "The policy keeps its id and every claim correlation. AI matchmaking re-runs against the new document.",
    replaceFileDone: "Document replaced — matchmaking re-queued",
    lastActivity: "Latest linked-claim activity",
  },
  alerts: {
    pageTitle: "Alert Page",
    chartTitle: "FinalClaimScore over time",
    legendTitle: "Key",
    legendEmpty: "Tick a claim in the table below to plot it.",
    watchlistTitle: "Watchlist",
    search: "Search watchlist…",
    colId: "ID",
    colChart: "Chart",
    colStatement: "Claim Statement",
    colCreated: "Claim Created Date",
    colStatus: "Status",
    overThreshold: "Over Threshold",
    underThreshold: "Under Threshold",
    empty: "Your watchlist is empty. Add claims from the Claim Repository Bank using the bell icon.",
    colTopic: "Topic",
    colCreatedDate: "Claim Created Date",
    colAdded: "Added",
    colRemove: "Remove",
    thresholdNote: "Compared against the global threshold of",
    granularity: "Granularity",
    granularityDay: "Day",
    granularityWeek: "Week",
    granularityMonth: "Month",
    granularityYear: "Year",
    chartEmpty:
      "No history yet for the ticked claims. Snapshots are captured hourly; use \"Snapshot scores now\" on Admin Settings to force one.",
    remove: "Remove from watchlist",
    removed: "Removed from watchlist",
    chartToggleFailed: "Could not update the chart selection.",
  },
  admin: {
    pageTitle: "Admin Settings",
    thresholdTitle: "Alert Threshold",
    thresholdDesc:
      "Global 0–100 threshold. A watched claim is \"Over Threshold\" on the Alert page when its FinalClaimScore is at or above this value.",
    thresholdLabel: "Threshold value",
    testUtilsTitle: "MVP Test Utilities",
    generateClaim: "Generate Generic Claim",
    generateClaimDesc:
      "Inserts one fully-populated Existing/Generic claim for demo and testing. Updates the \"last fetched\" time on the Claim Repository Bank.",
    generateClaimUtility: "Testing / MVP utility",
    generated: "A sample generic claim was added.",
    generateClaimTopic: "Pin to topic (optional)",
    generateClaimAnyTopic: "Any topic",
    snapshotTitle: "Snapshot scores now",
    snapshotDesc:
      "Captures a FinalClaimScore snapshot for every watched claim immediately, building Alert-page chart history without waiting for the hourly job.",
    snapshotAction: "Snapshot scores",
    snapshotDone: "score snapshots captured.",
    settingsTitle: "All settings",
    settingsDesc: "Every global setting the backend exposes, with its audit trail.",
    colKey: "Key",
    colValue: "Value",
    colUpdated: "Updated",
  },
  bell: {
    addTitle: "Add to Alert watchlist?",
    removeTitle: "Remove from Alert watchlist?",
    addBody:
      "This claim will be added to the Alert page watchlist so you can monitor its FinalClaimScore over time.",
    removeBody:
      "This claim will be removed from the Alert page watchlist and unticked from the chart.",
    add: "Add to watchlist",
    remove: "Remove",
    added: "Added to watchlist",
    removed: "Removed from watchlist",
  },
  coordinatedNetwork: {
    pageTitle: "Coordinated-Network Detector",
    placeholder:
      "F5 — Coordinated-Network Detector. Detailed layout, data fields, and detection logic are not yet defined and will be specified in a subsequent iteration of the PRD.",
  },
  status: {
    unreviewed: "Unreviewed",
    active: "Active",
    inactive: "Inactive",
    action_taken: "Action Taken",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    notFound: "We couldn't find what you were looking for.",
    liveModeUnavailable:
      "The backend API could not be reached. Check NEXT_PUBLIC_API_BASE_URL, or set NEXT_PUBLIC_API_MODE=mock to explore with sample data.",
    unavailable:
      "A backend dependency is unavailable right now. Please try again shortly.",
    unauthorized: "Your session has expired. Please sign in again.",
  },
} as const;
