/**
 * Centralised UI copy. i18n is deferred (PRD §5.3 asks for EN + Bahasa Indonesia);
 * keeping every user-facing string here makes adding `next-intl` later a drop-in.
 */
export const strings = {
  app: {
    name: process.env.NEXT_PUBLIC_APP_NAME ?? "Climate Immune System",
    shortName: "CIS",
    tagline: "A structured immune system for your information environment.",
  },
  nav: {
    claims: "Claim Repository Bank",
    policies: "Public Policy Bank",
    alerts: "Alert Page",
    admin: "Admin Settings",
    coordinatedNetwork: "Coordinated-Network Detector",
  },
  auth: {
    loginTitle: "Sign in",
    registerTitle: "Create an account",
    username: "Username",
    password: "Password",
    signIn: "Sign in",
    register: "Register",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    signingIn: "Signing in…",
    registering: "Creating account…",
    logout: "Log out",
    errRequired: "Username and password are required.",
    errInvalid: "Incorrect username or password.",
    errTaken: "That username is already taken.",
  },
  common: {
    seeAll: "See all",
    search: "Search",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    saved: "Saved",
    copy: "Copy",
    copied: "Copied to clipboard",
    download: "Download file",
    back: "Back",
    loading: "Loading…",
    noResults: "No results",
    allTopics: "All Topics",
    allYears: "All Year",
    allStatus: "All Status",
    lastFetched: "Last fetched",
  },
  claims: {
    pageTitle: "Claim Repository Bank",
    s1Title: "Existing Claims",
    s1Subtitle: "Generic Claim — confirmed circulating in public discourse",
    s2Title: "Non-Existing Claims",
    s2Subtitle: "Synthetic Claim — predicted by AI as likely to emerge",
    genericTag: "Existing Claim",
    syntheticTag: "Synthetic Claim",
    searchS1: "Search existing claims…",
    searchS2: "Search predicted claims…",
    firstCaught: "First caught",
    created: "Predicted",
    negativeStatements: "Negative statements",
    positiveStatements: "Positive statements",
    claimStatement: "Claim Statement",
    claimStatus: "Claim Status",
    scoreBreakdown: "Score Breakdown",
    topAccounts: "Top 5 Accounts",
    topAccountsNote:
      "Accounts contributing most to this claim's spread (supporting side).",
    debunkActivity: "Debunk Activity",
    prebunkActivity: "Prebunk Activity",
    correlatedPolicies: "Correlated Public Policies",
    correlatedPolicy: "Correlated Public Policy",
    noPolicies: "No correlated policies yet.",
    dormant: "Dormant",
    dormantHint: "No supporting or opposing volume — score not discounted.",
    eiSupporting: "EI (supporting)",
    eiOpposing: "EI (opposing) · diagnostic",
    seeAllGeneric: "All existing claims",
    seeAllSynthetic: "All predicted claims",
  },
  policies: {
    pageTitle: "Public Policy Bank",
    listTitle: "Public Policies",
    addPolicy: "Add Public Policy",
    addPolicyTitle: "Add a public policy",
    policyName: "Public policy name",
    policyNamePlaceholder: "e.g. Central Business District Congestion Charge",
    rolledOutDate: "Rolled-out date",
    file: "Policy document",
    fileHint: "PDF or Word document",
    fileReject: "Only PDF or Word documents are accepted.",
    search: "Search policies…",
    rolledOut: "Rolled Out",
    notRolledOut: "Not Rolled Out",
    processing: "Processing",
    processingHint:
      "AI matchmaking is linking and predicting claims for this policy. It will be available shortly.",
    exposureGeneric: "Correlated Existing Claims",
    exposureSynthetic: "Predicted Synthetic Claims",
    noGeneric: "No existing claims are linked to this policy yet.",
    noSynthetic: "No predicted claims have been generated for this policy yet.",
  },
  alerts: {
    pageTitle: "Alert Page",
    chartTitle: "FinalClaimScore over time",
    legendTitle: "Key",
    legendEmpty: "Tick a claim in the table below to plot it.",
    watchlistTitle: "Watchlist",
    search: "Search watchlist…",
    colId: "ID",
    colChart: "Chart",
    colStatement: "Claim Statement",
    colCreated: "Claim Created Date",
    colStatus: "Status",
    overThreshold: "Over Threshold",
    underThreshold: "Under Threshold",
    empty: "Your watchlist is empty. Add claims from the Claim Repository Bank using the bell icon.",
  },
  admin: {
    pageTitle: "Admin Settings",
    thresholdTitle: "Alert Threshold",
    thresholdDesc:
      "Global 0–100 threshold. A watched claim is \"Over Threshold\" on the Alert page when its FinalClaimScore is at or above this value.",
    thresholdLabel: "Threshold value",
    testUtilsTitle: "MVP Test Utilities",
    generateClaim: "Generate Generic Claim",
    generateClaimDesc:
      "Inserts one fully-populated Existing/Generic claim for demo and testing. Updates the \"last fetched\" time on the Claim Repository Bank.",
    generateClaimUtility: "Testing / MVP utility",
    generated: "A sample generic claim was added.",
  },
  bell: {
    addTitle: "Add to Alert watchlist?",
    removeTitle: "Remove from Alert watchlist?",
    addBody:
      "This claim will be added to the Alert page watchlist so you can monitor its FinalClaimScore over time.",
    removeBody:
      "This claim will be removed from the Alert page watchlist and unticked from the chart.",
    add: "Add to watchlist",
    remove: "Remove",
    added: "Added to watchlist",
    removed: "Removed from watchlist",
  },
  coordinatedNetwork: {
    pageTitle: "Coordinated-Network Detector",
    placeholder:
      "F5 — Coordinated-Network Detector. Detailed layout, data fields, and detection logic are not yet defined and will be specified in a subsequent iteration of the PRD.",
  },
  status: {
    unreviewed: "Unreviewed",
    active: "Active",
    inactive: "Inactive",
    action_taken: "Action Taken",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    notFound: "We couldn't find what you were looking for.",
    liveModeUnavailable:
      "The backend API is not available yet. Set NEXT_PUBLIC_API_MODE=mock to explore with sample data.",
  },
} as const;
